{
 "title": "Microgen",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Request",
   "type": "singlestat",
   "description": "broker server",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "expr": "sum(numOfRequests)" }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"localhost:4000\"}"
    }
   ]
  },
  {
   "title": "List Services",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "targets": [
    { "expr": "discovery_services" }
   ]
  },
  {
   "title": "Total Request Success",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "targets": [
    { "expr": "total_success_request_servies" }
   ]
  },
  {
   "title": "Total Request Failed",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 7 },
   "targets": [
    { "expr": "total_failed_request_servies" }
   ]
  },
  {
   "title": "Request Persecond",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(numOfRequests[5m])" }
   ]
  }
 ]
}